#!/bin/bash

serverUrl='http://jenkins-server.local:8080/'

javaUrl=${serverUrl}
javaUrl+='configure|grep env.value|tr " " "\n"|grep "(JDK)"|tr "\">" "\t"|cut -f1' 

comm1='curl --silent ' 
comm1+=${javaUrl}  

jobsList=${serverUrl}
jobsList+="api/json?pretty=true|grep name|grep -v All|tr -d ' \",'|tr ':' '\t'| cut -f2"

comm2="curl --silent ${jobsList}"

jobName=''
jdkVersion='' 

badInputParameters()
{
  echo "Usage: $0 JOBNAME JDK_VERSION"
  echo "where JOBNAME like: "
  cat jobsList
  echo "and JDK_VERSION like: "
  cat javaList
  exit
}

if [ $# -eq 2 ]; then
    eval $comm1 > javaList
    eval $comm2 > jobsList
    while read line1
       do
          if [ $1 == $line1 ]; then
             jobName+=$1
             echo "first argument: $line1"
             while read line2
                do
                   if [ $2 == $line2 ]; then
                      jdkVersion+=$2
                      echo "second argument: $line2"
                   fi
                done < javaList           
          fi 
       done < jobsList
    if [ "$jobName" != "" ] && [ "$jdkVersion" != "" ]; then
       echo $jobName $jdkVersion
       curl --silent -v ${serverUrl}/job/${jobName}/config.xml > configOld.xml
       jdk_old=`awk -F'[<>]' '/<jdk>/{print $3}' configOld.xml`
       sed "s#\(<jdk>\)${jdk_old}\(</jdk\)""#\1JDK ${jdkVersion}\2#g" configOld.xml > configNew.xml
       curl -v -X POST --data-binary @configNew.xml -H 'Content-Type: application/xml' ${serverUrl}/job/${jobName}/config.xml  
       echo "The JDK used for job: $jobName changed into JDK: $jdkVersion"
       rm configNew.xml configOld.xml
       exit
    else
       echo "Not correct parameters were used!"
       badInputParameters
    fi
else
   badInputParameters 
fi

