#!/bin/bash

serverUrl='http://jenkins-server.local:8080/'
javaUrl="${serverUrl}configure|grep env.value|tr ' ' '\n'|grep '(JDK)'|tr '\">' '\t'|cut -f1" 
jobsList="${serverUrl}api/json?pretty=true|grep name|grep -v All|tr -d ' \",'|tr ':' '\t'| cut -f2"

comm1="curl --silent ${javaUrl}"  
comm2="curl --silent ${jobsList}"

jobName=''
jdkVersion='' 

badInputParameters()
{
  echo "Usage: $0 JOBNAME JDK_VERSION"
  exit
}

if [ $# -eq 2 ]; then
    eval $comm1 > javaList 
    eval $comm2 > jobsName 
    while read line1
       do
          if [ $1 == $line1 ]; then
             jobName+=$1
             echo "first argument: $line1"
             while read line2
                do
                   if [ $2 == $line2 ]; then
                      jdkVersion+=$2
                      echo "second argument: $line2"
                   fi
	     done < javaList          
          fi 
       done < jobsName 
    if [ "$jobName" != "" ] && [ "$jdkVersion" != "" ]; then
       echo $jobName $jdkVersion
       curl --silent -v ${serverUrl}/job/${jobName}/config.xml > configOld.xml
       jdk_old=`awk -F'[<>]' '/<jdk>/{print $3}' configOld.xml`
       sed "s#\(<jdk>\)${jdk_old}\(</jdk\)""#\1JDK ${jdkVersion}\2#g" configOld.xml > configNew.xml
       curl -v -X POST --data-binary @configNew.xml -H 'Content-Type: application/xml' ${serverUrl}/job/${jobName}/config.xml  
       echo "The JDK used for job: $jobName changed into JDK: $jdkVersion"
       rm configNew.xml configOld.xml
       exit
    else
       badInputParameters
    fi
else
   badInputParameters 
fi

